name: Daily Shoe Scraper

on:
  schedule:
    # Runs daily at 9:00 IST (03:30 UTC)
    - cron: '30 3 * * *'
  workflow_dispatch:  # manual run option

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright sendgrid
          playwright install chromium

      - name: Run scraper
        env:
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: python shoe_scraper.py
